### PR TITLE
Add terraform script for pub/sub and enabling APIs

### PR DESCRIPTION
**Pull request by weix0011**
First PR!

### CODE REVIEW

**Review by tzehon — CHANGES_REQUESTED** [review]
1. If you run terraform init with version 0.14 and above you will get a warning about deprecated provider configuration blocks. Please make the required change to fix the warning

2. The project is currently hardcoded. Please change this as this means the script will not work for *any other project* except your own. The script should be able to work for any user with a GCP project.

**Comment by weix0011** [comment]
1. Added required providers block to fix the warning
2. Changed project id as a variable in variables.tf and terraform.tfvars

**Comment by tzehon** [comment]
1. Please always keep your fork up to date with upstream *before* doing anything. It is a best practice to always sync your fork with upstream before you start any work. Think of it as hand washing before having a meal. It will help you avoid merge conflicts in the future. The current repo is 2 commits behind upstream.

2. Squash your commits to keep a linear git history instead of pushing up multiple commits. See:
https://stackoverflow.com/a/15055649/106396
https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/about-pull-request-merges#squash-and-merge-your-pull-request-commits
https://cloudfour.com/thinks/squashing-your-pull-requests/
https://git-scm.com/book/en/v2/Git-Branching-Rebasing
These are standard industry best practices and it's good to pick them up early.

3. Please also include a .gitignore that takes into account intermediate Terraform artifacts. See - 
https://git-scm.com/docs/gitignore
https://www.atlassian.com/git/tutorials/saving-changes/gitignore

4. Practice with this current PR. If need be, feel free to close this PR and start a new one.

**Comment by weix0011** [comment]
1. Noted and synced with the upstream repository
2. Tried to rebase on this branch to give a clear message about what this PR is doing
3. Added a .gitignore file, but it is ignored in the parent .gitignore file in line 68 under ignore eclipse files. Shall I just keep it locally? For now I think it is better to edit the parent .gitignore file to include the terraform artifacts for simplicity.

**Comment by tzehon** [comment]
Looking good! Now that you're familiar with the workflow and common practices, please refactor the PR in the following ways to make it more production ready:
1. Do not set a default for the project id so the user will have to supply the project id

2. Make this first PR focused on PubSub only. This means the first PR will use Terraform to enable the PubSub API and create the requisite PubSub components. Subsequent components will be in future PRs. Keep each PR focused. standalone and small so it's easy to review and to use. In addition - 

3. Parameterize the names of the PubSub components as variables so the user can choose to supply their own names. For example, not everyone might want to call their topic "Inventory-outbound"

4. Refactor terraform.tfvars by removing the default for project id, related to point 1. Also, you can set the defaults for the PubSub components here. For example, if the user doesn't specify a topic name through --var flags, the default will be "Inventory-outbound", taken from the .tfvars file due to the precedence of variable loading (https://www.terraform.io/docs/language/values/variables.html#variable-definition-precedence).

5. Add a README.md that specifies how to run the Terraform script, similar to the one here: https://github.com/GoogleCloudPlatform/dataflow-sample-applications/tree/master/retail/retail-clickstream-application#deploy-using-terraform

6. Yes, modify the parent .gitignore.

**Comment by weix0011** [comment]
1. Removed the default project ID to prompt the user for input
2. Changed this PR to focus on pubsub related resources only
3. Parameterized pubsub components' names and added a type string constraint as the name only accepts string
4. Refactored terraform.tfvars to include the default values of pubsub components. There is also a default argument when declaring a variable. Can we indicate the default values there, too?
5. Added a README_TERRAFORM.md file as there is an existing README.md file. Is it fine if we have multiple md files?
6. Edited parent .gitignore to exclude terraform intermediate artifacts

**Comment by tzehon** [comment]
Regarding 5. -> You can remove the second README and modify the existing README by adding the 'Deploy using Terraform' section, same as here: https://github.com/GoogleCloudPlatform/dataflow-sample-applications/tree/master/retail/retail-clickstream-application#deploy-using-terraform

**Comment by weix0011** [comment]
Updated the existing README file with a terraform section and removed the second README file.

**Pull request closed without merging**
